8269230: C2: main loop in micro benchmark never executed
openjdk/jdk17 pull request #156
Opened 2021-06-28 08:20 UTC by rwestrel

The benchmark loop is roughly:

for (int i = 0; i < limit; i++) {
  if (!(i < max_jint && i > min_jint)) {
    uncommon_trap();
  }
}

which IfNode::fold_compares() tranforms to:

for (int i = 0; i < limit; i++) {
  if (!(i - min_jint - 1 <u -2)) {
    uncommon_trap();
  }
}

Range elimination then adjusts loop limits so the unsigned comparison
can be removed. The new limit is:

min(limit, max(-2 + min_jint + 1, min_jint)) = min(limit, min_jint) = min_jint

and the main loop is never executed.

The logic that protects against overflows during range check
elimination is what causes the main loop to never be executed. As a
fix, I propose delaying IfNode::fold_compares() if the resulting test
compares with a potential negative number which could then cause RC
overflow code to trigger. I think that would preserve the most
interesting cases for IfNode::fold_compares() when it comes to range
check elimination:

i >= 0 && i < array.length

2021-06-28 17:58 UTC, vnkozlov commented
I have to look but I think RCE mix up unsigned and signed expressions when calculating new limit. `min(limit, min_jint)` should be unsigned I think.

2021-06-28 18:31 UTC, vnkozlov reviewed
I have to look but I think RCE mix up unsigned and signed expressions when calculating new limit. `min(limit, min_jint)` should be unsigned I think.

2021-06-28 21:58 UTC, dean-long commented
What does the code tranform to after range check elimination?

2021-06-29 14:07 UTC, rwestrel commented
> I have to look but I think RCE mix up unsigned and signed expressions when calculating new limit. `min(limit, min_jint)` should be unsigned I think.

FYI, https://github.com/openjdk/jdk/pull/4362 changes that code but doesn't fix that issue.

2021-06-29 14:10 UTC, rwestrel commented
> What does the code transform to after range check elimination?

The main loop body has no test in the final code (with the proposed fix) and performance is on par with other micro benchmarks that this benchmark is compared with.

RCE has logic to handle signed comparisons so I expect that RCE is what removes the i < max_jint and i > min_jint from the main loop body.

2021-06-29 16:17 UTC, vnkozlov requested changes
I can't approve this for JDK 17. The issue is performance for very corner case but suggested fix may affect other cases. And this is not a bug IMHO - it is RFE which we should spend more time to investigate. I would suggest to defer it to JDK 18.

2021-06-29 23:49 UTC, vnkozlov commented
Okay. Maurizio and Paul explained to me in the bug report that it is very important code pattern in foreign memory API because C2 still does not support RCE over long index loops [8259609](https://bugs.openjdk.java.net/browse/JDK-8259609).
Taking this into account I think it is fine to push it into JDK 17 after testing which I will do.

2021-06-29 23:50 UTC, vnkozlov reviewed
I will test it and approve after that if everything (including performance) is good.

2021-06-30 00:02 UTC, vnkozlov commented
Add the test to test/micro/org/openjdk/bench/jdk/incubator/foreign/

2021-06-30 03:36 UTC, vnkozlov commented
tier1-3 testing passed. Performance results will be tomorrow.

2021-06-30 09:05 UTC, rwestrel commented
> Add the test to test/micro/org/openjdk/bench/jdk/incubator/foreign/

done

2021-06-30 11:08 UTC, rwestrel commented
/contributor add mcimadamore

2021-06-30 11:13 UTC, mcimadamore commented
I tried this patch on my machine - I can confirm it solves the problem, and that the benchmark shows similar numbers in all iterations now. Thanks for taking care of this!

2021-06-30 11:13 UTC, rwestrel commented
> > Add the test to test/micro/org/openjdk/bench/jdk/incubator/foreign/
> 
> done

And I added Maurizio as contributor of this change so he gets credit for the test case.

2021-06-30 17:04 UTC, vnkozlov approved these changes
Performance results are good - no regression.
You need second review.

2021-06-30 20:28 UTC, veresov approved these changes
Looks reasonable

2021-07-01 07:39 UTC, rwestrel commented
@vnkozlov @veresov thanks for the reviews

2021-07-01 07:40 UTC, rwestrel commented
/integrate

2021-07-01 07:41 UTC, closed without merging