8269697: JNI_GetPrimitiveArrayCritical() should not accept object array
openjdk/jdk17 pull request #185
Opened 2021-06-30 20:11 UTC by zhengyu123

GetPrimitiveArrayCritical() is supposed to only be used with primitive array types, but nothing prevents current implementation from accepting object arrays (please see attached test case in bug).

My purposed fix is not very friendly, it crashes JVM if a none primitive array is passed in, but I am sure what to expect in this scenario.

Specification people, please comment. Thanks!

2021-06-30 23:57 UTC, kimbarrett requested changes

2021-06-30 23:57 UTC, kimbarrett commented on src/hotspot/share/prims/jni.cpp
> +  guarantee(a->is_typeArray(), "Primitive array only");
I think an assert here is more usual.  This is JNI - we don't make guarantees (pun slightly intentional).  If you want error reporting, use -Xcheck:jni; the appropriate check and reporting is already there.

2021-07-01 01:03 UTC, kimbarrett approved these changes
Looks good.

2021-07-01 04:59 UTC, dholmes-ora requested changes
The change looks good.

We should add a testcase in runtime/jni/checked/ to ensure Xcheck:jni catches this.

Thanks,
David

2021-07-01 08:45 UTC, shipilev commented
Hold on. This introduces the behavioral change _for the worse_, right? More specifically, the current callers-with-object-array would now get `TypeArrayKlass::cast()`-ed to improper class with unknown consequences. _Hopefully_ it would be a JVM crash, but it might as well be incorrect execution. Old code would execute fine with most GCs (= the ones using GCLocker). Would it be saner to do a copy of object array if such a request is detected?

I believe it warrants a CSR discussion, and therefore postponement to JDK 18.

2021-07-01 08:50 UTC, pliden commented
The spec (https://docs.oracle.com/en/java/javase/16/docs/specs/jni/functions.html#getprimitivearraycritical-releaseprimitivearraycritical) says:

> Returns a pointer to the array elements, or NULL if the operation fails.

I interpret this as we're allowed to return NULL in this case. Operation failed because of invalid input.

2021-07-01 08:56 UTC, shipilev commented
Yes, returning `NULL` would be much saner here. That would alleviate my concern: the out-of-spec users would have a clear failure result. (It should be done before trying to lock/pin the object, of course).

2021-07-01 12:33 UTC, zhengyu123 commented
The spec also says: 

> Therefore we need to check its return value against NULL for possible out of memory situations.

it suggests that returning NULL solely due to out of memory

2021-07-01 13:17 UTC, zhengyu123 commented
Close this PR and move to 18 for further discussion.

2021-07-01 13:17 UTC, closed without merging