8269879: [PPC64] C2: Math.rint intrinsic uses wrong rounding mode
openjdk/jdk17 pull request #215
Opened 2021-07-05 20:05 UTC by TheRealMDoerr

We need to replace the frin and xvrdpi instructions which use a wrong rounding mode. xvrdpic is available with Power7. We can simply switch off RoundDoubleMode intrinsics for older processors (which are outdated).
Note that xvrdpic requires RN=0b00 to use the correct rounding mode. These 2 bits are 0 by default (see "Registers Specified during Process Initialization" in [1]) and are treated as "Limited-Access Bits" (see "2.2.1.2. Limited-Access Bits" in [1] for preservation rules).

[1] "64-Bit ELF V2 ABI Specification" http://cdn.openpowerfoundation.org/wp-content/uploads/resources/leabi/leabi-20170510.pdf

2021-07-05 20:42 UTC, RealLucy requested changes
The changes look good so far.

You are mentioning that the now used instruction is available from Power7 and that for older versions of the Power spec, the intrinsic should be disabled. I am missing such a change, probably in vm_version_ppc.cpp.

Furthermore, you mention that the instruction needs a special (non-default) setting of the rounding mode control flags. How can such flag setting be assured? 
Thanks, Lutz

2021-07-05 20:46 UTC, TheRealMDoerr commented
> The changes look good so far.

Thanks!

> You are mentioning that the now used instruction is available from Power7 and that for older versions of the Power spec, the intrinsic should be disabled. I am missing such a change, probably in vm_version_ppc.cpp.

See change in Matcher::match_rule_supported(int opcode).

> Furthermore, you mention that the instruction needs a special (non-default) setting of the rounding mode control flags. How can such flag setting be assured?

No, it's the default setting (see referenced ABI chapters).

2021-07-06 05:53 UTC, RealLucy approved these changes
Thanks for your clarification! My "prefabricated" opinion blurred the sights on reality. All fine!

2021-07-06 06:53 UTC, GoeLin approved these changes
LGTM

2021-07-07 12:50 UTC, TheRealMDoerr commented
Thanks for the reviews!
/integrate

2021-07-07 12:52 UTC, closed without merging