JDK-8270203
openjdk/jdk17 pull request #239
Opened 2021-07-09 19:45 UTC by erikj79

Add missing make dependency in Main.gmk.

2021-07-11 03:17 UTC, tbell29552 approved these changes
Looks good

2021-07-12 12:28 UTC, magicus requested changes

2021-07-12 12:28 UTC, magicus commented on make/Main.gmk
> +  # jdk.jfr-gensrc uses TOOL_JFR_GEN from buildtools-hotspot
The comment and the code do not match. I assume the comment is incorrect.

2021-07-13 05:53 UTC, erikj79 commented
/integrate

2021-07-13 05:55 UTC, closed without merging